#!/usr/bin/env bash

if [[ $* == *-a* ]]; then
    branch_name=$(git branch --all | grep -v "HEAD" | sed -e "s/\*/ /g" | sed -e "s/remotes\/origin\///g" | fzf | tr -d ' ')
else
    branch_name=$(git for-each-ref --format='%(refname:short)' refs/heads/ | fzf | tr -d ' ')
fi

if [ -n "$branch_name" ]; then
    git checkout "$branch_name"
fi
