#!/usr/bin/env bash

languages=`echo "python cpp c typescript lua nodejs golang" | tr ' ' '\n'`
core_utils=`echo "xargs find sed awk" | tr ' ' '\n'`

selected=`printf "$languages\n$core_utils" | fzf`
read -p "query: " query

if printf $languages | grep -qs $selected; then
    tmux neww bash -c "curl cht.sh/$selected/$(echo $query | tr ' ' '+') | bat --paging=always; exit"
else
    tmux neww bash -c "curl cht.sh/$selected~$query | bat --paging=always; exit"
fi


